# Generated by Django 5.2.8 on 2025-12-13 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('canonical_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('safety_category', models.CharField(default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingredients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductAffiliateLink',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('store', models.CharField(max_length=100)),
                ('marketplace', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'product_affiliate_links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('product_ing_id', models.BigAutoField(db_column='product_ing_id', primary_key=True, serialize=False)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('concentration', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'product_ingredients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSafetyCache',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('skincare', 'skincare'), ('makeup', 'makeup'), ('haircare', 'haircare')], max_length=20)),
                ('product_id', models.BigIntegerField()),
                ('safety_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('safety_category', models.CharField(blank=True, max_length=10, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'product_safety_cache',
                'unique_together': {('category', 'product_id')},
            },
        ),
    ]
