# Generated by Django 5.2.8 on 2025-12-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HaircareProduct',
            fields=[
                ('haircare_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('skin_type', models.TextField(blank=True, null=True)),
                ('staging_product_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'haircare_products',
                'managed': False,
            },
        ),
    ]
